export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const ADMIN_PROFILE_REQUEST = "ADMIN_PROFILE_REQUEST";
export const ADMIN_PROFILE_SUCCESS = "ADMIN_PROFILE_SUCCESS";
export const ADMIN_PROFILE_FAIL = "ADMIN_PROFILE_FAIL";

export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
